### ISSUE TITLE
Resources menu size incorrect (Mobile) 

### ISSUE THREAD

**Issue by dillionlim** [chemolyds/codsite-v3#16]
## Bug description
The menu icon and right part of the resources on mobile pages are off the visible area. When scrolling right to get to it, the resulting overlay does not cover the entire width. 

## To Reproduce
Go to https://chem.isodn.org/resources on a mobile device. 

## Expected behavior
Menu button and all resources are contained within the screen. 

## Priority
P4

## Screenshots/Video
![Screenshot_2023-07-31-14-58-34-57_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/chemolyds/codsite-v3/assets/101955194/e36d7042-8006-4ae5-a9dc-377fdcd74bca)

## Mobile/Tablet
 - Device: OPPO A74
 - OS: Android Version 13
 - Screen size: 6.43 in
 - Resolution: 2400×1080
 - Mobile Browser: Chrome
 - Version: Chrome 115.0.5790.138

## Additional context
NIL

**Comment by Jerdan1980** [comment]
Fixed, thanks for fixing!
