### ISSUE TITLE
[BUG] Wrong label on top LH side

### ISSUE THREAD

**Issue by dillionlim** [chemolyds/codsite-v3#19]
**Bug Description**
When the menu is opened, Jerdan1980 is shown on the top left hand corner instead of CODSite.

**To Reproduce**
1. Go to https://chem.isodn.org/ on any device and click on the menu icon. 

**Expected behavior**
CODSite is shown instead of Jerdan1980. 

**Screenshots/Video**
![Screenshot_2023-07-31-14-58-34-57_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/chemolyds/codsite-v3/assets/101955194/e36d7042-8006-4ae5-a9dc-377fdcd74bca)

**Priority**
P4

**Smartphone**
 - Device: OPPO A74
 - OS: Android Version 13
 - Screen size: 6.43 in
 - Resolution: 2400×1080
 - Mobile Browser: Chrome
 - Version: Chrome 115.0.5790.138

**Additional context**
NIL

**Comment by Jerdan1980** [comment]
Fixed via #33
