### ISSUE TITLE
[REQUEST] Add a lib for CODSCourses MDX files

### ISSUE THREAD

**Issue by Jerdan1980** [chemolyds/codsite-v3#31]
**Is your feature request related to a problem? Please describe.**
MDX pages need to be consumed and processed before they are displayed on the site.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Include:
- Details of the technical implementation
Create and implement ~/src/lib/courses.ts containing `getCoursesData()`, `getAllCoursesIds()`, and `getCourseData()`. Check other files in the same folder for examples.
- Tradeoffs made in design decisions
Need to update files in case of changes to file strucutre
- Caveats and considerations for the future
Check above.

**Describe alternatives you've considered**
NIL

**Additional context**
NIL

**Comment by Jerdan1980** [comment]
Thanks for your contribution!

**Comment by Sloopyyy** [comment]
thank
